# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6919c9229b504b30e524b7b5e664b863067d3b8a70b656cc6ecbce151d1fb6f890defd9872dd5c8afceb626db6194cad23c8900bc0e654817ef853572e87e0f5

test:
  secret_key_base: 7870bb7ba8b7106520ab1c54c2773034b2722c6c7cc805e9cf2b50be5ac36548bcc10d919624a9bb27889a4943e1e6744055e56b54916e29e27ebbe268455781

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
