# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d29533906362a9959db8b68981f5ea1219ef696eb56dbba79d0bef8b88b2b7a6c09e9e8c2845ddd8db3f2af71ac916b3ff478300267fb84fbbeab5941840f226

test:
  secret_key_base: 4606ae95e11090023543b713ba8da6184b3b7705b97e5ea43ed96c66577840ab7a1656a6c3189421d56362303bb0810294fba1b04bf356406e783f2b5e3582aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
